#!/bin/bash
#set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
sudo add-apt-repository ppa:certbot/certbot
sudo apt --yes install python-certbot-apache
sudo systemctl reload apache2
echo "What domain name are we securing? (Do NOT include the www):"
read domain
sudo certbot --apache -d $domain -d www.$domain
echo "Finished! Go to Step 9"
