#!/bin/bash
#set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
sudo apt --yes install apache2
sudo ufw allow OpenSSH
sudo ufw allow "Apache Full"
sudo ufw enable
sudo cp /etc/apache2/apache2.conf /etc/apache2/apache2.conf.bak
echo "What is your primary domain? Enter WITHOUT the www:"
read domain
echo "ServerName $domain" | sudo tee -a /etc/apache2/apache2.conf
sudo a2enmod rewrite
sudo systemctl restart apache2
echo "Finished! Go to Step 6 in the guide."
